#!/bin/bash

export XDG_CONFIG_HOME="$SNAP_USER_COMMON/.config"
export XDG_DATA_HOME="$SNAP_USER_COMMON/.local/share"

mkdir -p "$XDG_CONFIG_HOME"
mkdir -p "$XDG_DATA_HOME"

export GST_PLUGIN_SYSTEM_PATH="$SNAP/winehq/usr/lib/i386-linux-gnu/gstreamer-1.0:$SNAP/winehq/usr/lib/x86_64-linux-gnu/gstreamer-1.0:$GST_PLUGIN_SYSTEM_PATH"

exec "$@"
